target_sources(layout_scion PRIVATE
    HTMLAnchorElement.swift
    HTMLAreaElement.swift
    HTMLBodyElement.swift
    HTMLBRElement.swift
    HTMLButtonElement.swift
    HTMLCanvasElement.swift
    HTMLDivElement.swift
    HTMLElement.swift
    HTMLFormControlElement.swift
    HTMLFrameOwnerElement.swift
    HTMLFrameSetElement.swift
    HTMLHtmlElement.swift
    HTMLImageElement.swift
    HTMLInputElement.swift
    HTMLLegendElement.swift
    HTMLMapElement.swift
    HTMLOptionElement.swift
    HTMLOptGroupElement.swift
    HTMLSelectElement.swift
    HTMLSlotElement.swift
    HTMLTableCellElement.swift
    HTMLTableElement.swift
    HTMLTablePartElement.swift
    HTMLTextAreaElement.swift
    HTMLTextFormControlElement.swift
    HTMLWBRElement.swift
)
add_subdirectory(canvas)
add_subdirectory(shadow)
